import Header from "../src/components/shared/header/Index.js";
import Aside from "../src/components/shared/aside/Index.js";
import { useEffect, useState } from "react";
import "bootstrap/dist/css/bootstrap.css";
// import Cookies from "js-cookie";

import "../styles/globals.css";

import Head from "next/head";

function MyApp({ Component, pageProps }) {
  const [isDark, setIsDark] = useState(false);

  const HandleIsDark = () => {
    const storedIsDark = JSON.parse(localStorage.getItem("isDark"));
    const newIsDark = !storedIsDark;

    setIsDark(newIsDark);
    localStorage.setItem("isDark", JSON.stringify(newIsDark));
  };

  console.log("isDark from _app: ", isDark);
  useEffect(() => {
    const storedIsDark = JSON.parse(localStorage.getItem("isDark"));

    if (storedIsDark !== null) {
      setIsDark(storedIsDark);
    } else {
      localStorage.setItem("isDark", JSON.stringify(isDark));
    }
  }, [isDark]);

  if (Component.getLayOut) {
    return Component.getLayOut(<Component {...pageProps} />);
  }

  return (
    <>
      <Head>
        <title>Saad Elnady Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <div className={isDark ? " app bg-dark2" : "app  bg-light"}>
        <Header isDark={isDark} HandleIsDark={HandleIsDark} />

        <div className="container-fluid">
          <div className="row    justify-content-evenly">
            <Aside isDark={isDark} />
            <Component {...pageProps} />
          </div>
        </div>
      </div>
    </>
  );
}

// MyApp.getInitialProps = async (props) => {
//   return {
//     props: {},
//   };
// };

export default MyApp;
