import Header from "@/sharedComponents/header/Index.js";
import Aside from "@/sharedComponents/aside/Index.js";

import "bootstrap/dist/css/bootstrap.css";

import "styles/globals.css";

import Head from "next/head";
import { useEffect, useState } from "react";
import { Toaster } from "react-hot-toast";

const MyApp = ({ Component, pageProps }) => {
  const [isDark, setIsDark] = useState(false);

  const HandleIsDark = () => {
    const storedIsDark = JSON.parse(localStorage.getItem("isDark"));
    const newIsDark = !storedIsDark;

    setIsDark(newIsDark);
    localStorage.setItem("isDark", JSON.stringify(newIsDark));
  };

  useEffect(() => {
    const storedIsDark = JSON.parse(localStorage.getItem("isDark"));

    if (storedIsDark !== null) {
      setIsDark(storedIsDark);
    } else {
      localStorage.setItem("isDark", JSON.stringify(isDark));
    }
  }, [isDark]);

  if (Component.getLayOut) {
    return Component.getLayOut(<Component {...pageProps} />);
  }
  return (
    <>
      <Head>
        <title>Saad Elnady Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <div className={isDark ? "bg-dark2" : " bg-light"}>
        <Header isDark={isDark} HandleIsDark={HandleIsDark} />

        <div className="container-fluid">
          <div className="row justify-content-evenly">
            <Aside isDark={isDark} />
            <Component {...pageProps} isDark={isDark} />
          </div>
        </div>
      </div>
      <Toaster position="top-right" reverseOrder={false} />
    </>
  );
};

export default MyApp;

// MyApp.getInitialProps = async (props) => {
//   return {
//     props: {},
//   };
// };
