import Head from "next/head";
import Certificates from "../src/components/certificates/Index";
const CertificatesPage = ({ isDark }) => {
  return (
    <>
      <Head>
        <title>Saad Elnady certificates</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <Certificates isDark={isDark} />
    </>
  );
};

export default CertificatesPage;
