import Head from "next/head";
import Contact from "@/components/contact/Index";

const ContactPage = ({ isDark }) => {
  return (
    <>
      <Head>
        <title> contact me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <Contact isDark={isDark} />
    </>
  );
};

export default ContactPage;
