import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";

export default function Home() {
  const router = useRouter();

  useEffect(() => {
    (() => {
      router.push(`/home`);
    })();
  }, [router]);
  return (
    <>
      <Head>
        <title>Saad Elnady Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
    </>
  );
}
