import Head from "next/head";
import MyProjects from "../src/components/projects/Index";

const ProjectsPage = ({ isDark, filteredProjects }) => {
  return (
    <>
      <Head>
        <title>Saad Elnady projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <MyProjects filteredProjects={filteredProjects} isDark={isDark} />
    </>
  );
};

export default ProjectsPage;

export const getStaticProps = async () => {
  const response = await fetch("https://api.github.com/users/saadelnady/repos");
  const projects = await response.json();
  const filteredProjects = projects
    .filter((project) => project.homepage)
    .sort(function (a, b) {
      return (
        new Date(b.order_date || b.created_at || b.updated_at) -
        new Date(a.order_date || a.created_at || a.updated_at)
      );
    });
  return {
    props: { filteredProjects },
    revalidate: 5,
  };
};
