import Head from "next/head";

const Resume = ({ isDark, mySkills }) => {
  return (
    <>
      <Head>
        <title>Saad Elnady resume</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <div
        className={`resume col-12 col-lg-7 rounded shadow px-2 px-md-5 py-5
         ${isDark ? "bg-dark " : " text-dark bg-light"}`}
      >
        <div className="special-heading">
          <h1
            className={`d-inline-block p-2 ${
              isDark ? "text-light bg-dark" : "text-dark bg-light "
            }`}
          >
            Resume
          </h1>
        </div>
        <ul>
          <li className="about px-3">
            <div
              className={`p-4 text-white rounded ${
                isDark ? "bg-dark2 text-light" : "bg-white text-dark"
              } `}
            >
              <p className={isDark ? "text-light fs-5" : "text-black fs-5"}>
                Jul 2023 - Oct 2023
              </p>
              <p className="text-orange fs-3">
                Information Technology Institute (ITI)
              </p>
              <i className="text-blue">Full Stack using MERN Track</i>
              <ul className="mt-3">
                Skills:
                {mySkills.map((skill, index) => {
                  return (
                    <li
                      className={`ps-4 mt-3 my-skills ${
                        isDark ? "text-light" : "text-dark"
                      }`}
                      key={index}
                    >
                      {skill}
                    </li>
                  );
                })}
              </ul>
            </div>
          </li>
        </ul>
      </div>
    </>
  );
};

export default Resume;
export const getStaticProps = async () => {
  const mySkills = [
    `HTML/CSS: Proficiency in creating semantic HTML markup. Advanced
  CSS skills, including CSS Grid, Flexbox, and CSS pre-processors
  like Sass.`,
    `JavaScript: Strong understanding of core JavaScript concepts.
  Familiarity with modern JavaScript features (ES6+).`,
    `Frontend Frameworks: Experience with popular frontend frameworks
  like Angular, React. Understanding of component-based
  architecture.`,
    `  Responsive Design and CSS Frameworks: Knowledge of responsive
  design principles. Experience with CSS frameworks like
  Bootstrap.`,
    ` Version Control: Proficiency in using Git for version control,
  including branching and merging.`,
    ` Debugging Tools: Familiarity with browser developer tools for
  debugging and profiling frontend code.`,
    ` Collaboration and Communication: Ability to collaborate
  effectively within a team environment. Strong communication
  skills, both written and verbal.`,
    ` Problem Solving: Analytical and problem-solving skills to
  identify and fix frontend issues efficiently.`,
    `UI/UX Design Awareness: Basic understanding of UI/UX design
  principles for effective collaboration with designers.
`,
    `Continuous Learning: Willingness to learn and adapt to new
frontend technologies and best practices.`,
  ];
  return {
    props: {
      mySkills,
    },
  };
};
