import Skills from "../src/components/skills/Index";

import Head from "next/head";
const SkillsPage = ({ isDark }) => {
  return (
    <>
      <Head>
        <title>Saad Elnady skills</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <Skills isDark={isDark} />
    </>
  );
};

export default SkillsPage;
